class_name CamLimitEnum

enum  {
  FULL_LIMIT,
  LIMIT_BOTTOM_RIGHT,
  LIMIT_BOTTOM_LEFT,
  LIMIT_TOP_RIGHT,
  LIMIT_TOP_LEFT,
  LIMIT_X_AXIS,
  LIMIT_Y_AXIS,
  LIMIT_ALL_BUT_TOP,
  LIMIT_ALL_BUT_LEFT,
  LIMIT_ALL_BUT_RIGHT,
  LIMIT_ALL_BUT_BOTTOM
}
