extends Node

signal player_landed(area, position)
signal player_diying(area, position, entity_type)
signal player_died()
signal player_jumped()
signal player_rotate(dir)
signal player_land()
signal player_explode()
signal player_fall()
signal player_dash(direction)
signal player_slippering()

signal gem_collected(color, position, frames)
signal slide_animation_ended(animation_name)
signal checkpoint_reached(checkpoint_object)
signal checkpoint_loaded()

#UI Signals
signal Play_button_pressed()
signal Stats_button_pressed()
signal Settings_button_pressed()
signal Quit_button_pressed()
signal Go_to_main_menu_pressed()
signal menu_box_rotated()
signal pause_menu_enter()
signal pause_menu_exit()

#Settings signals
signal Fullscreen_toggled(value)
signal Vsync_toggled(value)
signal Screen_size_changed(value)
signal on_action_bound(action, key)
signal tab_changed()
signal focus_changed()
signal keyboard_action_biding()

#tetris
signal tetris_lines_removed()

#brick breaker
signal brick_broken(color, position)
signal bouncing_ball_removed(ball)


func emit_player_landed(area, position): emit_signal("player_landed", area, position)
func emit_player_diying(area, position, entity_type): emit_signal("player_diying", area, position, entity_type)
func emit_player_died(): emit_signal("player_died")
func emit_player_slippering(): emit_signal("player_slippering")
func emit_player_jumped(): emit_signal("player_jumped")
func emit_player_rotate(dir): emit_signal("player_rotate", dir)
func emit_player_land(): emit_signal("player_land")
func emit_player_explode(): emit_signal("player_explode")
func emit_player_fall(): emit_signal("player_fall")
func emit_player_dash(dir): emit_signal("player_dash", dir)
func emit_gem_collected(color, position, frames): emit_signal("gem_collected", color, position, frames)
func emit_slide_animation_ended(animation_name): emit_signal("slide_animation_ended", animation_name)
func emit_checkpoint_reached(checkpoint): emit_signal("checkpoint_reached", checkpoint)
func checkpoint_loaded(): emit_signal("checkpoint_loaded")
func emit_Play_button_pressed(): emit_signal("Play_button_pressed")
func emit_Stats_button_pressed(): emit_signal("Stats_button_pressed")
func emit_Settings_button_pressed(): emit_signal("Settings_button_pressed")
func emit_Quit_button_pressed(): emit_signal("Quit_button_pressed")
func emit_Go_to_main_menu_pressed(): emit_signal("Go_to_main_menu_pressed")
func emit_menu_box_rotated(): emit_signal("menu_box_rotated")
func emit_pause_menu_enter(): emit_signal("pause_menu_enter")
func emit_pause_menu_exit(): emit_signal("pause_menu_exit")
func emit_Fullscreen_toggled(fullscreen): emit_signal("Fullscreen_toggled", fullscreen)
func emit_Vsync_toggled(vsync): emit_signal("Vsync_toggled", vsync)
func emit_Screen_size_changed(size): emit_signal("Screen_size_changed", size)
func emit_on_action_bound(action, key): emit_signal("on_action_bound", action, key)
func emit_tab_changed(): emit_signal("tab_changed")
func emit_focus_changed(): emit_signal("focus_changed")
func emit_keyboard_action_biding(): emit_signal("keyboard_action_biding")
func emit_tetris_lines_removed(): emit_signal("tetris_lines_removed")
func emit_brick_broken(color, position): emit_signal("brick_broken", color, position)
func emit_bouncing_ball_removed(ball): emit_signal("bouncing_ball_removed", ball)
