extends Node

func _ready():
  set_process(false)

signal player_landed(area, position)
signal player_diying(area, position, entity_type)
signal player_died()
signal player_jumped()
signal player_rotate(dir)
signal player_land()
signal player_explode()
signal player_fall()
signal player_dash(direction)
signal player_slippering()

signal gem_collected(color, position, frames)
signal slide_animation_ended(animation_name)
signal checkpoint_reached(checkpoint_object)
signal checkpoint_loaded()

#UI Signals
signal menu_box_rotated()
signal pause_menu_enter()
signal pause_menu_exit()
signal menu_button_pressed(menu_button)

#Settings signals
signal Fullscreen_toggled(value)
signal Vsync_toggled(value)
signal Screen_size_changed(value)
signal on_action_bound(action, key)
signal tab_changed()
signal focus_changed()
signal keyboard_action_biding()
signal sfx_volume_changed(volume)
signal music_volume_changed(volume)

#tetris
signal tetris_lines_removed()

#brick breaker
signal brick_broken(color, position)
signal bouncing_ball_removed(ball)
signal picked_powerup()
signal break_breaker_win()
signal brick_breaker_start()

#piano
signal piano_note_pressed(note)
signal piano_note_released(note)
signal page_flipped()
signal wrong_piano_note_played()

func emit_player_landed(area, position): emit_signal("player_landed", area, position)
func emit_player_diying(area, position, entity_type): emit_signal("player_diying", area, position, entity_type)
func emit_player_died(): emit_signal("player_died")
func emit_player_slippering(): emit_signal("player_slippering")
func emit_player_jumped(): emit_signal("player_jumped")
func emit_player_rotate(dir): emit_signal("player_rotate", dir)
func emit_player_land(): emit_signal("player_land")
func emit_player_explode(): emit_signal("player_explode")
func emit_player_fall(): emit_signal("player_fall")
func emit_player_dash(dir): emit_signal("player_dash", dir)
func emit_gem_collected(color, position, frames): emit_signal("gem_collected", color, position, frames)
func emit_slide_animation_ended(animation_name): emit_signal("slide_animation_ended", animation_name)
func emit_checkpoint_reached(checkpoint): emit_signal("checkpoint_reached", checkpoint)
func checkpoint_loaded(): emit_signal("checkpoint_loaded")
func emit_menu_button_pressed(menu_button): emit_signal("menu_button_pressed", menu_button) #see MenuButtons
func emit_menu_box_rotated(): emit_signal("menu_box_rotated")
func emit_pause_menu_enter(): emit_signal("pause_menu_enter")
func emit_pause_menu_exit(): emit_signal("pause_menu_exit")
func emit_Fullscreen_toggled(fullscreen): emit_signal("Fullscreen_toggled", fullscreen)
func emit_Vsync_toggled(vsync): emit_signal("Vsync_toggled", vsync)
func emit_Screen_size_changed(size): emit_signal("Screen_size_changed", size)
func emit_sfx_volume_changed(volume): emit_signal("sfx_volume_changed", volume)
func emit_music_volume_changed(volume): emit_signal("music_volume_changed", volume)
func emit_on_action_bound(action, key): emit_signal("on_action_bound", action, key)
func emit_tab_changed(): emit_signal("tab_changed")
func emit_focus_changed(): emit_signal("focus_changed")
func emit_keyboard_action_biding(): emit_signal("keyboard_action_biding")
func emit_tetris_lines_removed(): emit_signal("tetris_lines_removed")
func emit_brick_broken(color, position): emit_signal("brick_broken", color, position)
func emit_bouncing_ball_removed(ball): emit_signal("bouncing_ball_removed", ball)
func emit_picked_powerup(): emit_signal("picked_powerup")
func emit_break_breaker_win(): emit_signal("break_breaker_win")
func emit_brick_breaker_start(): emit_signal("brick_breaker_start")
func emit_piano_note_pressed(note): emit_signal("piano_note_pressed", note)
func emit_piano_note_released(note): emit_signal("piano_note_released", note)
func emit_page_flipped(): emit_signal("page_flipped")
func emit_wrong_piano_note_played(): emit_signal("wrong_piano_note_played")
