public enum CameraLimit
    {
        NO_LIMITS,
        FULL_LIMIT,
        LIMIT_BOTTOM_RIGHT,
        LIMIT_BOTTOM_LEFT,
        LIMIT_TOP_RIGHT,
        LIMIT_TOP_LEFT,
        LIMIT_X_AXIS,
        LIMIT_Y_AXIS,
        LIMIT_ALL_BUT_TOP,
        LIMIT_ALL_BUT_LEFT,
        LIMIT_ALL_BUT_RIGHT,
        LIMIT_ALL_BUT_BOTTOM,
        LIMIT_LEFT,
        LIMIT_RIGHT,
        LIMIT_TOP,
        LIMIT_BOTTOM
    }
